// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IJwtAuth is an autogenerated mock type for the IJwtAuth type
type IJwtAuth struct {
	mock.Mock
}

// JwtAuthMiddleware provides a mock function with given fields:
func (_m *IJwtAuth) JwtAuthMiddleware() gin.HandlerFunc {
	ret := _m.Called()

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// Sign provides a mock function with given fields: userId, username
func (_m *IJwtAuth) Sign(userId string, username string) (string, error) {
	ret := _m.Called(userId, username)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(userId, username)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userId, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
