name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Download modules
      run: go mod download

    - name: Install Swaggo
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Build swagger
      run: swag init

    - name: Build
      run: go build -v ./...

    - name: Test and coverage
      run: go test -v -race -covermode=atomic -coverprofile coverage.out ./...

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)